version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      root-deps:
        update-types:
          - "minor"
          - "major"

  - package-ecosystem: "npm"
    directory: "/apps/worker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      worker-deps:
        update-types:
          - "minor"
          - "major"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      web-deps:
        update-types:
          - "minor"
          - "major"

  - package-ecosystem: "gradle"
    directory: "/apps/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      android-deps:
        update-types:
          - "minor"
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        update-types:
          - "minor"
          - "major"
