import React, { useState } from 'react';
import { getPreviewUrl, getVideoPosterUrl } from '../api';

interface EventThumbnailProps {
  slug: string;
  previewPhotoId: string | null;
  /** Video previews need their POSTER (a real JPEG) — an <img> can't render video bytes. */
  fileType?: string | null;
  cacheVersion?: number | null;
  alt: string;
  className?: string;
  /** Shown when there is no preview photo, or a video's poster hasn't been generated yet. */
  fallback: React.ReactNode;
}

/**
 * Event/album card thumbnail. Renders the plain image preview for photos, or the video's poster
 * (falling back to `fallback` if the poster 404s — e.g. not yet generated by the nightly job) for
 * an event whose representative photo is a video, instead of pointing an <img> at a video URL.
 */
const EventThumbnail: React.FC<EventThumbnailProps> = ({
  slug,
  previewPhotoId,
  fileType,
  cacheVersion,
  alt,
  className,
  fallback,
}) => {
  const [posterFailed, setPosterFailed] = useState(false);
  const isVideo = fileType === 'video/mp4';

  if (!previewPhotoId || (isVideo && posterFailed)) {
    return <>{fallback}</>;
  }

  const src = isVideo
    ? getVideoPosterUrl(slug, previewPhotoId, cacheVersion ?? undefined)
    : getPreviewUrl(slug, previewPhotoId, fileType ?? undefined, cacheVersion ?? undefined);

  return (
    <img
      src={src}
      alt={alt}
      className={className}
      loading="lazy"
      onError={isVideo ? () => setPosterFailed(true) : undefined}
    />
  );
};

export default EventThumbnail;
